export enum Datatype {
  INT = 'int',
  SMALLINT = 'smallint',
  BIGINT = 'bigint',
  FLOAT = 'float',
  DOUBLE = 'double',
  CHAR = 'char',
  VARCHAR = 'varchar',
  TEXT = 'text',
  DATE = 'date',
  TIME = 'time',
  TIMESTAMP = 'timestamp',
  BOOLEAN = 'boolean',
  BIT = 'bit',
  VARBIT = 'varbit',
  JSON = 'json',
  UUID = 'uuid',
  //XML = 'xml',
  //DECIMAL = 'decimal',
  SERIAL = 'serial',
  SMALLSERIAL = 'smallserial',
  BIGSERIAL = 'bigserial',
}
